name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        always-auth: true
        node-version: '20.x'
        registry-url: https://registry.npmjs.org
        scope: '@calvinlq'
    - name: Install dependencies
      run: npm install && npm run dev
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
